---

- name: Time Synchronization

  hosts: jakarta,serverd.lab.example.com

  roles:

    - rhel-system-roles.timesync

  post_tasks:

    - name: Set timezone

      timezone:

        name: Asia/Kuching

      notify: reboot host

  handlers:

    - name: reboot host

      reboot:
